import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { FC, PropsWithChildren } from 'react';
import { privacyPolicyUrl, termsOfUseUrl } from '@/app/links';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Login',
  //description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container prose mx-auto flex min-h-screen flex-col items-center justify-center dark:prose-invert">
          <div>{children}</div>

          <div className="mt-4">
            {privacyPolicyUrl && <a href={privacyPolicyUrl}>Privacy Policy</a>}
            {privacyPolicyUrl && termsOfUseUrl && ' '}
            {termsOfUseUrl && <a href={termsOfUseUrl}>Terms of Use</a>}
          </div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
