import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { FC, PropsWithChildren } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Login',
  //description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container prose mx-auto flex min-h-screen items-center justify-center dark:prose-invert">
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
